class_name: OctAttention
max_octree_level: 12
context_size: 1024
token_num: 255
layer_num: 3
head_num: 4
abs_pos_embed_dim: 12
occ_embed_dim: 128
level_embed_dim: 6
octant_embed_dim: 4
hidden_dimension: 300
pos_max_len: 5000
level_k: 4
pos_embed: True
