defaults:
  - default.yaml
  - model: ehem.yaml
  - data: ford_ehem.yaml

train:
  type: 'ford'
  lr: 0.0001
  lr_scheduler:
    step_size: 3
  epoch: 8

hydra:
  run:
    dir: ./outputs/ford/${now:%Y-%m-%d}/${now:%H-%M-%S}